Repository OpenTOSCA/container, pull requests merged in 2018-08, with the labels that each got.

#69 [Feature] Improve environment variable handling for DockerContainer NodeTypes
  org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELDockerContainerTypePluginHandler.java
Labels: needs review

#71 [Bug] Fix planbuilder deployment pairs
  org.opentosca.planbuilder.prephase.plugin.fileupload/src/org/opentosca/planbuilder/prephase/plugin/fileupload/core/PrePhasePlugin.java
Labels: bug, needs review

#73 Fix/ia invocation without sudo
  org.opentosca.bus.management.plugins.remote.service.impl/src/org/opentosca/bus/management/plugins/remote/service/impl/ManagementBusPluginRemoteServiceImpl.java
Labels: needs review

#76 fixes issue when starting Containers from ImageID
  org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/BPELTerminationProcessBuilder.java
  org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELDockerContainerTypePluginHandler.java
  org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELOpenMTCDockerContainerTypePluginHandler.java
  org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/core/DockerContainerTypePlugin.java
  org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/core/OpenMTCDockerContainerTypePlugin.java
  org.opentosca.planbuilder.type.plugin.ubuntuvm/src/org/opentosca/planbuilder/type/plugin/ubuntuvm/bpel/BPELUbuntuVmTypePluginHandler.java
Labels: bug, needs review

#77 fixes issues with input and outpus of plans
  org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/helpers/EmptyPropertyToInputInitializer.java
  org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/helpers/PropertyMappingsToOutputInitializer.java
Labels: enhancement, needs review

#74 Fix ia invocation
  org.opentosca.bus.management.plugins.remote.service.impl/META-INF/artifacttypes/Script.xml
  org.opentosca.bus.management.plugins.remote.service.impl/src/org/opentosca/bus/management/plugins/remote/service/impl/ManagementBusPluginRemoteServiceImpl.java
Labels: needs review

#80 Feature/situations
  org.opentosca.container.api/META-INF/MANIFEST.MF
  org.opentosca.container.api/OSGI-INF/CsarController.xml
  org.opentosca.container.api/OSGI-INF/SituationsController.xml
  org.opentosca.container.api/src/org/opentosca/container/api/Activator.java
  org.opentosca.container.api/src/org/opentosca/container/api/controller/RootController.java
  org.opentosca.container.api/src/org/opentosca/container/api/controller/SituationsController.java
  org.opentosca.container.api/src/org/opentosca/container/api/dto/PropertyDTO.java
  org.opentosca.container.api/src/org/opentosca/container/api/dto/situations/SituationDTO.java
  org.opentosca.container.api/src/org/opentosca/container/api/dto/situations/SituationListDTO.java
  org.opentosca.container.api/src/org/opentosca/container/api/dto/situations/SituationTriggerDTO.java
  org.opentosca.container.api/src/org/opentosca/container/api/dto/situations/SituationTriggerInputDTO.java
  org.opentosca.container.api/src/org/opentosca/container/api/dto/situations/SituationTriggerInstanceDTO.java
  org.opentosca.container.api/src/org/opentosca/container/api/dto/situations/SituationTriggerListDTO.java
  org.opentosca.container.api/src/org/opentosca/container/api/service/InstanceService.java
  org.opentosca.container.control/src/org/opentosca/container/control/ServiceBindingTracker.java
  org.opentosca.container.control/src/org/opentosca/container/control/impl/OpenToscaControlServiceImpl.java
  org.opentosca.container.core/META-INF/MANIFEST.MF
  org.opentosca.container.core/META-INF/persistence.xml
  org.opentosca.container.core/src/org/opentosca/container/core/Activator.java
  org.opentosca.container.core/src/org/opentosca/container/core/next/model/Situation.java
  org.opentosca.container.core/src/org/opentosca/container/core/next/model/SituationTrigger.java
  org.opentosca.container.core/src/org/opentosca/container/core/next/model/SituationTriggerInstance.java
  org.opentosca.container.core/src/org/opentosca/container/core/next/model/SituationTriggerInstanceProperty.java
  org.opentosca.container.core/src/org/opentosca/container/core/next/model/SituationTriggerProperty.java
  org.opentosca.container.core/src/org/opentosca/container/core/next/repository/SituationRepository.java
  org.opentosca.container.core/src/org/opentosca/container/core/next/repository/SituationTriggerInstanceRepository.java
  org.opentosca.container.core/src/org/opentosca/container/core/next/repository/SituationTriggerRepository.java
  org.opentosca.container.core/src/org/opentosca/container/core/next/trigger/SituationListener.java
  org.opentosca.container.core/src/org/opentosca/container/core/next/trigger/SituationTriggerInstanceListener.java
  org.opentosca.container.feature/feature.xml
  org.opentosca.container.product/org.opentosca.container.product
  org.opentosca.planbuilder.core.bpel/META-INF/resources/assignVarFromVarWithXpath2Queries.xml
  org.opentosca.planbuilder.core.bpel/META-INF/resources/assignVarWithLiteral.xml
  org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/BPELBuildProcessBuilder.java
  org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/context/BPELPlanContext.java
  org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/fragments/BPELProcessFragments.java
  org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/handlers/BPELPlanHandler.java
  org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/helpers/SituationTriggerRegistration.java
  org.opentosca.planbuilder.model/src/org/opentosca/planbuilder/model/utils/ModelUtils.java
  org.opentosca.planbuilder.postphase.plugin.monitoring/src/org/opentosca/planbuilder/postphase/plugin/monitoring/bpel/impl/BPELMonitoringPlugin.java
  org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELDockerContainerTypePluginHandler.java
  org.opentosca.planbuilder.type.plugin.patternbased/META-INF/MANIFEST.MF
  org.opentosca.planbuilder.type.plugin.patternbased/META-INF/resources/assignStringVarWithXpath2Query.xml
  org.opentosca.planbuilder.type.plugin.patternbased/build.properties
  org.opentosca.planbuilder.type.plugin.patternbased/pom.xml
  org.opentosca.planbuilder.type.plugin.patternbased/src/org/opentosca/planbuilder/type/plugin/patternbased/Activator.java
  org.opentosca.planbuilder.type.plugin.patternbased/src/org/opentosca/planbuilder/type/plugin/patternbased/bpel/BPELContainerPatternBasedHandler.java
  org.opentosca.planbuilder.type.plugin.patternbased/src/org/opentosca/planbuilder/type/plugin/patternbased/bpel/BPELPatternBasedPlugin.java
  pom.xml
Labels: enhancement, needs review

#75 Feature: Class for validating/correcting NCNames
  org.opentosca.planbuilder/src/org/opentosca/planbuilder/NCName.java
Labels: in progress
